OPENAI_API_KEY_PEDRO: 'sk-proj-0DeoJoZ1H5jqYY3au0XNT3BlbkFJM1luznDOIkFufI4JxAnb'
OPENAI_API_KEY: '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'
PINECONE_API_KEY: 'f0959a65-92d6-4bda-b33b-cbba5b5a6f5b'
GOOGLE_API_KEY: 'AIzaSyBcLFSmTitHbf83L4A6H73_v9g2AMJDRHU'

OPENAI_API_KEY_SINERJI: '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'
QROQ_API_KEY: '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'
